/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        regLabel = new javax.swing.JLabel();
        detailsLabel = new javax.swing.JLabel();
        fNameLabel = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        fNameIn = new javax.swing.JTextField();
        lNameIn = new javax.swing.JTextField();
        emailIn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordIn = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        securityQBox = new javax.swing.JComboBox();
        secQLabel = new javax.swing.JLabel();
        securityAnswerIn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        regButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        rePassIn = new javax.swing.JPasswordField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jToggleButton1.setText("jToggleButton1");

        regLabel.setText("Register");

        detailsLabel.setText("Please enter details below");

        fNameLabel.setText("First Name: ");

        lNameLabel.setText("Last Name: ");

        fNameIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameInActionPerformed(evt);
            }
        });

        lNameIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameInActionPerformed(evt);
            }
        });

        emailIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInActionPerformed(evt);
            }
        });

        jLabel1.setText("Email Address: ");

        passwordIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInActionPerformed(evt);
            }
        });

        jLabel2.setText("Password: ");

        jLabel3.setText("Re-enter Password: ");

        securityQBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mother's maiden name?", "Street you grew up on?", "Name of your first pet?", "You favourite animal?" }));
        securityQBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQBoxActionPerformed(evt);
            }
        });

        secQLabel.setText("Security Question: ");

        securityAnswerIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnswerInActionPerformed(evt);
            }
        });

        jLabel4.setText("Security Question Answer: ");

        regButton.setText("Register");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(detailsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(regLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNameLabel)
                            .addComponent(fNameLabel)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(secQLabel)
                            .addComponent(jLabel4)
                            .addComponent(backButton))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(securityAnswerIn)
                            .addComponent(passwordIn)
                            .addComponent(emailIn)
                            .addComponent(fNameIn)
                            .addComponent(lNameIn)
                            .addComponent(securityQBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rePassIn))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel)
                    .addComponent(fNameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLabel)
                    .addComponent(lNameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rePassIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityQBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secQLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityAnswerIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton)
                    .addComponent(backButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fNameInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameInActionPerformed

    private void lNameInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameInActionPerformed

    private void passwordInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInActionPerformed

    private void securityQBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        // TODO add your handling code here:
        String fName = fNameIn.getText();
        String lName = lNameIn.getText();
        String password = passwordIn.getText();
        String email = emailIn.getText();
        String passwordCheck = rePassIn.getText();
        String secAnswer = securityAnswerIn.getText();
        
        if(fName.contains("")|| lName.contains("") || password.contains("") || email.contains("") || passwordCheck.contains("") || secAnswer.contains("")){
            fNameIn.setText("");
            lNameIn.setText("");
            passwordIn.setText("");
            emailIn.setText("");
            rePassIn.setText("");
            securityAnswerIn.setText("");
            RegisterMessage reg = new RegisterMessage();
            reg.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "The details you entered are invalid \n Please try again! ", "Click OK to continue", JOptionPane.ERROR_MESSAGE);
            fNameIn.setText("");
            lNameIn.setText("");
            passwordIn.setText("");
            emailIn.setText("");
            rePassIn.setText("");
            securityAnswerIn.setText("");
            
        }
    }//GEN-LAST:event_regButtonActionPerformed

    private void emailInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInActionPerformed

    private void securityAnswerInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnswerInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnswerInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JTextField emailIn;
    private javax.swing.JTextField fNameIn;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField lNameIn;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JPasswordField passwordIn;
    private javax.swing.JPasswordField rePassIn;
    private javax.swing.JButton regButton;
    private javax.swing.JLabel regLabel;
    private javax.swing.JLabel secQLabel;
    private javax.swing.JTextField securityAnswerIn;
    private javax.swing.JComboBox securityQBox;
    // End of variables declaration//GEN-END:variables
}
